/*
  @author edgar.benedetto@unah.hn
  @date 19/02/2021
  @version 1.0

*/

--- Inciso #3 Examen
CREATE TABLE TBL_REG_CLI_20171033802(
  REG_CUSTOMER_ID NUMBER PRIMARY KEY,
  REG_CUST_FIRST_NAME VARCHAR(20),
  REG_CUST_STREET_ADDRESS VARCHAR(60),
  REG_CUST_CITY VARCHAR2(30),
  UPDATE_DATE TIMESTAMP
);

CREATE SEQUENCE SQ_TBL_REG_CLI_20171033802
START WITH 1
INCREMENT BY 1; 

DECLARE 
/*
   TYPE FILA IS RECORD(
     REG_CUSTOMER_ID DEMO_CUSTOMERS.CUSTOMER_ID%TYPE,
     REG_CUST_FIRST_NAME DEMO_CUSTOMERS.CUST_FIRST_NAME%TYPE,
     REG_CUST_STREET_ADDRESS DEMO_CUSTOMERS.CUST_STREET_ADDRESS1%TYPE,
     REG_CUST_CITY DEMO_CUSTOMERS.CUST_CITY%TYPE
   );
*/

   TYPE TABLA_REG_CLI IS TABLE OF DEMO_CUSTOMERS%ROWTYPE INDEX BY PLS_INTEGER;
   
   --- Variable para almacenar todos los registros del Bulk Collect
   DATOS_CLI TABLA_REG_CLI;
   
   --- Variable para recorrer los registros obtenidos
   ITERACION NUMBER(10):= 0;
   
   ID_CUST NUMBER:=SQ_TBL_REG_CLI_20171033802;
BEGIN
  
   SELECT DEMO_CUSTOMERS.CUSTOMER_ID, DEMO_CUSTOMERS.CUST_FIRST_NAME, DEMO_CUSTOMERS.CUST_STREET_ADDRESS1, DEMO_CUSTOMERS.CUST_CITY
   BULK COLLECT INTO DATOS_CLI FROM DEMO_CUSTOMERS;
   COMMIT;
   SAVEPOINT FIRST_RETURN;
   
   WHILE (ITERACION<SQL%ROWCOUNT) LOOP
    IF ID_CUST = REG_CUSTOMER_ID THEN
     INSERT INTO TBL_REG_CLI_20171033802 (REG_CUSTOMER_ID, REG_CUST_FIRST_NAME, REG_CUST_STREET_ADDRESS, REG_CUST_CITY) VALUES(DATOS_CLI(ITERACION+1).CUSTOMER_ID, DATOS_CLI(ITERACION+1).CUST_FIRST_NAME, DATOS_CLI(ITERACION+1).CUST_STREET_ADDRESS1, DATOS_CLI(ITERACION+1).CUST_CITY);
     ITERACION:=ITERACION+1;
    END IF;
      SQ_TBL_REG_CLI_20171033802:= SQ_TBL_REG_CLI_20171033802.NEXTVAL;
   END LOOP;
   
  EXCEPTION 
    WHEN DUP_VAL_ON_INDEX THEN
       DBMS_OUTPUT.PUT_LINE('EL CLIENTE NO SE INSERTARA PORQUE YA EXISTE');
       DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL ERROR ES:'|| SQLCODE);
       DBMS_OUTPUT.PUT_LINE('EL ERROR ES:'|| SQLERRM);
       ROLLBACK TO SAVEPOINT FIRST_RETURN;
    WHEN OTHERS THEN
      ROLLBACK TO SAVEPOINT FIRST_RETURN;
END;

CREATE OR REPLACE TRIGGER TG_SQ_TBL_REG_CLI_20171033802
AFTER INSERT ON TBL_REG_CLI_20171033802
FOR EACH ROW
DECLARE
  ID_CUST NUMBER:=SQ_TBL_REG_CLI_20171033802;
BEGIN
  UPDATE TBL_REG_CLI_20171033802 SET UPDATE_DATE = SYSTIMESTAMP WHERE REG_CUSTOMER_ID = ID_CUST;
END;


