/*
  @author edgar.benedetto@unah.hn
  @date 19/02/2021
  @version 1.0

*/

CREATE USER BD_VENTAS IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT ADMINISTRADORES TO BD_VENTAS;

GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS.DEMO_CUSTOMERS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS.DEMO_ORDER_ITEMS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS.DEMO_ORDERS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS.DEMO_PRODUCT_INFO TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS.DEMO_STATES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS.DEMO_USERS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS.DEPT TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS.EMP TO ADMINISTRADORES;

