GRANT SELECT ON BD_CENSO.PAISES TO ADMINISTRADORES;

GRANT SELECT,INSERT,DELETE,UPDATE ON BD_CENSO.POBLACIONES TO ADMINISTRADORES;

GRANT SELECT,INSERT,DELETE,UPDATE ON BD_BICICLETAS.PRODUCTS TO ADMINISTRADORES;