/*
  @author edgar.benedetto@unah.hn N.Cuenta 20171033802
  @date 26/03/2021
  @decription Examen Práctico #2 BDII Sección 1400 I PAC 2021 
  @name_file SYSTEM.sql
  @version 1.0
  
  Ejercicio 1-3
    1. Creación del usuario BD_COUNTRIES_EXAM para restaurar la base de datos del examen
    2. Otorgar priviligeios del rol Administrador
    3. Restaurar la base de datos creando una nueva conexiónn
    4. Permitir seleccionar, insertar, eliminar y actualizar las tablas de la base de datos restaurada
*/


CREATE USER BD_COUNTRIES_EXAM IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT ADMINISTRADORES TO BD_COUNTRIES_EXAM;

GRANT SELECT,INSERT,UPDATE,DELETE ON BD_COUNTRIES_EXAM.COUNTRIES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_COUNTRIES_EXAM.DEPARTMENTS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_COUNTRIES_EXAM.EMPLOYEES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_COUNTRIES_EXAM.JOB_GRADES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_COUNTRIES_EXAM.JOB_HISTORY TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_COUNTRIES_EXAM.JOBS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_COUNTRIES_EXAM.LOCATIONS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_COUNTRIES_EXAM.REGIONS TO ADMINISTRADORES;

