/*
  @author edgar.benedetto@unah.hn
  @date 18/02/2021
  @version 1.0
  
  Ejercicios #5 - #12
*/

--- Inciso #5
CREATE USER BD_ANALISTA IDENTIFIED BY analista
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

--- Inciso #6
GRANT ADMINISTRADORES TO BD_ANALISTA;

GRANT SELECT,INSERT,UPDATE,DELETE ON BD_ANALISTA.COCHES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_ANALISTA.MECANICOS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_ANALISTA.LOGS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_ANALISTA.TRABAJOS TO ADMINISTRADORES;