/*
  @author edgar.benedetto@unah.hn N.Cuenta 20171033802
  @date 23/03/2021
  @decription Tarea N3 BDII Sección 1400 I PAC 2021 
  @name_file SYSTEM.sql
  @version 1.0
  
  Ejercicio 1-3
    1. Creación del usuario BD_VENTAS_TAREA_N3 para restaurar la base de datos VENTAS
    2. Otorgar priviligeios del rol Administrador
    3. Restaurar la base de datos creando una nueva conexión
    4. Permitir seleccionar, insertar, eliminar y actualizar las tablas de la base de datos restaurada
*/

CREATE USER BD_VENTAS_TAREA_N3 IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT ADMINISTRADORES TO BD_VENTAS_TAREA_N3;

GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_TAREA_N3.DEMO_CUSTOMERS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_TAREA_N3.DEMO_ORDER_ITEMS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_TAREA_N3.DEMO_ORDER TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_TAREA_N3.DEMO_PODUCT_INFO TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_TAREA_N3.DEMO_STATES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_TAREA_N3.DEMO_USERS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_TAREA_N3.DEPT TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_TAREA_N3.EMP TO ADMINISTRADORES;

/*
  Ejercicio 4-7
    1. Creación del usuario BD_EMPRESA_TAREA_N3 para restaurar la base de datos EMPRESA
    2. Otorgar priviligeios del rol Administrador
    3. Restaurar la base de datos creando una nueva conexión
    4. Permitir seleccionar, insertar, eliminar y actualizar las tablas de la base de datos restaurada
*/

CREATE USER BD_EMPRESA_TAREA_N3 IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT ADMINISTRADORES TO BD_EMPRESA_TAREA_N3;

GRANT SELECT,INSERT,UPDATE,DELETE ON BD_EMPRESA_TAREA_N3.COUNTRIES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_EMPRESA_TAREA_N3.DEPARTMENTS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_EMPRESA_TAREA_N3.EMPLOYEES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_EMPRESA_TAREA_N3.JOB_GRADES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_EMPRESA_TAREA_N3.JOB_HISTORY TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_EMPRESA_TAREA_N3.JOBS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_EMPRESA_TAREA_N3.LOCATIONS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_EMPRESA_TAREA_N3.REGIONS TO ADMINISTRADORES;
