/*
  @author edgar.benedetto@unah.hn N.Cuenta 20171033802
  @date 23/03/2021
  @decription Tarea N4 BDII Sección 1400 I PAC 2021 
  @name_file SYSTEM.sql
  @version 1.0
  
    1. Creación del usuario para restaurar la base de datos Dietas_Ganaderas 
    2. Otorgar Privilegios de administrador  
    3. Otorgar Privilegios para realizar transacciones en las tablas de la base de datos

*/
CREATE USER BD_DIETAS_GANADERAS IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT ADMINISTRADORES TO BD_DIETAS_GANADERAS;

GRANT SELECT,INSERT,UPDATE,DELETE ON BD_GANADERAS.ALIMENTOS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_GANADERAS.ALIMENTOSXDIETA TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_GANADERAS.ANIMALES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_GANADERAS.ANIMALESXDIETA TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_GANADERAS.DIETA TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_GANADERAS.NITRIENTE TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_GANADERAS.NUTRIENTESXALIMENTO TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_GANADERAS.TOMAS TO ADMINISTRADORES;