OPTIONS (SKIP='1')
LOAD DATA
APPEND INTO TABLE ANIMALES
(
ANIMALID CHAR TERMINATED BY ", " ,
ESPECIE CHAR TERMINATED BY ", " ,
NOMBRE CHAR TERMINATED BY ", " ,
PESO INTEGER EXTERNAL TERMINATED BY ", " ,
FECHANACIMIENTO DATE "YYYY-MM-DD" TERMINATED BY ", " ,
LUGARCODIGO CHAR TERMINATED BY ", " 
)
