/*
  @author edgar.benedetto@unah.hn
  @date 19/02/2021
  @version 1.0


  Examen #1 Practico
*/

--- Inciso #1
CREATE USER BD_VENTAS_EXAM IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT ADMINISTRADORES TO BD_VENTAS_EXAM;

GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_EXAM.DEMO_CUSTOMERS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_EXAM.DEMO_ORDER_ITEMS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_EXAM.DEMO_ORDERS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_EXAM.DEMO_PRODUCT_INFO TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_EXAM.DEMO_STATES TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_EXAM.DEMO_USERS TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_EXAM.DEPT TO ADMINISTRADORES;
GRANT SELECT,INSERT,UPDATE,DELETE ON BD_VENTAS_EXAM.EMP TO ADMINISTRADORES;