---Clase #2
CREATE USER BD_BICICLETAS IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

CREATE ROLE ADMINISTRADORES;

GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY PROCEDURE, ALTER ANY TABLE, ALTER ANY PROCEDURE, DROP ANY TABLE, DROP ANY PROCEDURE TO ADMINISTRADORES;

GRANT ADMINISTRADORES TO BD_BICICLETAS;

---Consulta para verificar los roles creados

SELECT * FROM DBA_ROLES;

---Consulta para verificar los privilegios asignados a un rol

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='ADMINISTRADORES';

---Clase #3
CREATE USER BD_CENSO_EXAM IDENTIFIED BY 123;
GRANT ADMINISTRADORES TO BD_CENSO;

GRANT SELECT ON CX_BD_CENSO_EXAM.PAISES TO ADMINISTRADORES;